function plot_lod_scores()

%PLOT_LOD_SCORES plots the lod scores generated by multipool.

hfig=figure('Position',[1         635        1440         170]);
hold all;

offset_for_new_chromosome=0;

colors_plot=cbrewer('qual', 'Dark2',16);
all_LOD=[];

for iChromosome=1:16
    
    tmp=importdata(['../data_bioinformatics/multipool_LOD/output_chr' num2str(iChromosome) '.txt']);
    
    x=tmp.data(:,1);
    
    y=tmp.data(:,3);
    
    h=plot(x+offset_for_new_chromosome,y,'linewidth',2)
    all_LOD=vertcat(all_LOD,y);
    
    offset_for_new_chromosome=offset_for_new_chromosome+x(end);
    
    set(h,'Color', colors_plot(iChromosome,:),'LineWidth', 1)
    
end

ylim([-1 40])

ylabel('LOD score')
xlabel('Position chromosome')

Set_fig_RE(hfig,9,9,14)

filename='Figure LOD score';
export_fig_specific_path(filename, '-pdf','-transparent','-nocrop');
end